### ISSUE TITLE
Please provide how to build pytorch from source for ROCm-3.5.1

### ISSUE THREAD

**Issue by cwt** [xuhuisheng/rocm-gfx803#11]
I'm using CentOS 8 which the latest ROCm that works with gfx803 is 3.5.1.
I can't install your pytorch wheel because it was built with difference version of glibc available on CentOS 8, so I have to build it from the source.

**Comment by Lunatik00** [comment]
first, the versions here are for the user extended support made by xuhuisheng the versions are not for the old versions you can use containers provided by the rocm team to have the versions of torch available for your version of rocm, for build there ara the official rocm team instructions for the pakage modified for rocm https://github.com/ROCmSoftwarePlatform/pytorch#from-source there is also  the tensorflow rocm implementation in https://github.com/ROCmSoftwarePlatform/tensorflow-upstream , this is easier because they have a script so you just have to run build_rocm_python3 , the prerequisite is a specific bazel version depending on the version you need to install

**Comment by xuhuisheng** [comment]
Here is relation building steps for python and ROCm. Please notice the `USE_ROCM=1` part.
<https://github.com/xuhuisheng/rocm-build/blob/master/gfx803/README.md#pytorch-190-crashed-on-gfx803>

But as we know, the ROCm-3.5.1 is an aged version which released before two years, it is possible that apis haved been changed a lot.
